"""
Early Warning Recommendation Module
====================================
Maps model risk predictions to non-clinical academic, lifestyle, and student-support
early warning guidance.
"""

RECOMMENDATION_MAP = {
    0: {
        "level": "Low Risk",
        "action_tier": "General Wellness Maintenance",
        "recommendation": (
            "Encourage student to maintain current healthy academic, sleep, and lifestyle habits. "
            "Suggest optional engagement in routine student wellness programs."
        )
    },
    1: {
        "level": "Mild Risk",
        "action_tier": "Self-Monitoring & Guided Balance",
        "recommendation": (
            "Suggest regular self-monitoring of weekly workload, exam preparation schedules, and sleep patterns. "
            "Provide stress management and time-allocation resources."
        )
    },
    2: {
        "level": "Moderate Risk",
        "action_tier": "Peer & Workshop Engagement",
        "recommendation": (
            "Recommend joining peer study groups and attending university academic counseling or "
            "stress-reduction workshops."
        )
    },
    3: {
        "level": "High Risk",
        "action_tier": "Advisory & Academic Support Flag",
        "recommendation": (
            "Flag for early warning advisory; recommend consultation with academic support counselors "
            "and student life advisory services."
        )
    },
    4: {
        "level": "Critical Risk",
        "action_tier": "Immediate Professional Consultation",
        "recommendation": (
            "Immediate early warning notification; strongly advise direct consultation with university "
            "psychological support services and counseling center professionals."
        )
    }
}


def get_recommendation(risk_class):
    """
    Returns recommendation details for a predicted risk class (0 to 4).
    """
    risk_class = int(risk_class)
    if risk_class not in RECOMMENDATION_MAP:
        raise ValueError(f"Invalid risk class: {risk_class}. Expected integer between 0 and 4.")
    return RECOMMENDATION_MAP[risk_class]


def format_student_assessment_report(student_id, predicted_class, class_probabilities=None):
    """
    Formats a clean, non-clinical summary report for a student risk assessment.
    """
    rec_info = get_recommendation(predicted_class)
    
    report_lines = [
        "--------------------------------------------------",
        f"STUDENT PSYCHOLOGICAL RISK ASSESSMENT REPORT",
        "--------------------------------------------------",
        f"Student Identifier : {student_id}",
        f"Predicted Risk Level: {rec_info['level']} (Class {predicted_class})",
        f"Action Tier         : {rec_info['action_tier']}",
        "--------------------------------------------------",
        f"Recommendation:",
        f"{rec_info['recommendation']}",
        "--------------------------------------------------"
    ]
    
    if class_probabilities is not None:
        class_names = ['Low Risk', 'Mild Risk', 'Moderate Risk', 'High Risk', 'Critical Risk']
        report_lines.append("Class Probabilities:")
        for idx, prob in enumerate(class_probabilities):
            report_lines.append(f"  - {class_names[idx]}: {prob:.2%}")
        report_lines.append("--------------------------------------------------")
        
    report_lines.append("DISCLAIMER: This report is generated by an academic research framework")
    report_lines.append("for early warning risk classification and DOES NOT constitute a clinical diagnosis.")
    report_lines.append("--------------------------------------------------")
    
    return "\n".join(report_lines)
